=== nfwork/dbfound/src/main/resources/META-INF/model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
			xmlns:d="http://dbfound.googlecode.com/model" targetNamespace="http://dbfound.googlecode.com/model">

	<xsd:element name="model">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="query" type="d:query_type">
					<xsd:unique name="queryParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
					<xsd:unique name="queryFilterUnique">
						<xsd:selector xpath="d:filter"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute" type="d:execute_type">
					<xsd:unique name="executeParamUnique">
						<xsd:selector xpath="d:param"/>
						<xsd:field xpath="@name"/>
					</xsd:unique>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="connectionProvide" />
		</xsd:complexType>
		<xsd:unique name="modelParamUnique">
			<xsd:selector xpath="d:param"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelQueryUnique">
			<xsd:selector xpath="d:query"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
		<xsd:unique name="modelExecuteUnique">
			<xsd:selector xpath="d:execute"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:complexType name="query_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element name="sql" type="d:sql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="filter" type="d:filter_type">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="verifier">
				<xsd:complexType>
					<xsd:attribute name="express" />
					<xsd:attribute name="message" />
					<xsd:attribute name="code" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="pagerSize" />
		<xsd:attribute name="exportSize" />
		<xsd:attribute name="maxPagerSize" />
		<xsd:attribute name="name" />
		<xsd:attribute name="queryTimeout" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="entity" />
		<xsd:attribute name="connectionProvide" />
		<xsd:attribute name="printContext" />
	</xsd:complexType>

	<xsd:complexType name="filter_type">
		<xsd:attribute name="active">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="condition" />
		<xsd:attribute name="express" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="value" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="execute_type">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="param" type="d:param_type" />
			<xsd:element minOccurs="0" name="sqls" type="d:sqls_type" />
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="adapter" />
		<xsd:attribute name="connectionProvide" />
	</xsd:complexType>

	<xsd:complexType name="param_type">
		<xsd:attribute name="name" use="required" />
		<xsd:attribute name="dataType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="varchar" />
					<xsd:enumeration value="number" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="boolean" />
					<xsd:enumeration value="collection" />
					<xsd:enumeration value="file" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="scope">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="session" />
					<xsd:enumeration value="request" />
					<xsd:enumeration value="param" />
					<xsd:enumeration value="cookie" />
					<xsd:enumeration value="header" />
					<xsd:enumeration value="outParam" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoSession">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCookie">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="ioType">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="out" />
					<xsd:enumeration value="in" />
					<xsd:enumeration value="both" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="UUID">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="batchAssign">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="emptyAsNull">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="fileNameParam" />
		<xsd:attribute name="innerPath" />
	</xsd:complexType>

	<xsd:complexType name="sql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlTrim_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="sqlPart_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="if" />
					<xsd:enumeration value="elseif" />
					<xsd:enumeration value="else" />
					<xsd:enumeration value="for" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoCompletion">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="autoClearComma">
			<xsd:simpleType>
				<xsd:restriction base="xsd:NMTOKEN">
					<xsd:enumeration value="true" />
					<xsd:enumeration value="false" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="condition" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="separator" />
		<xsd:attribute name="begin" />
		<xsd:attribute name="end" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="sqls_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="requiredDataType">
						<xsd:simpleType>
							<xsd:restriction base="xsd:NMTOKEN">
								<xsd:enumeration value="list" />
								<xsd:enumeration value="map" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="caseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="whenSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="when" use="required" />
	</xsd:complexType>

	<xsd:complexType name="otherwiseSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql" type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="batchSql_type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="executeSql" type="d:executeSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchExecuteSql"  type="d:batchExecuteSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="querySql" type="d:querySql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="java" type="d:java_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="caseSql" type="d:caseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="whenSql" type="d:whenSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="otherwiseSql" type="d:otherwiseSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="collisionSql" type="d:collisionSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="batchSql" type="d:batchSql_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="execute">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="query">
				<xsd:complexType>
					<xsd:attribute name="modelName" />
					<xsd:attribute name="name" />
					<xsd:attribute name="currentPath" />
					<xsd:attribute name="rootPath" />
					<xsd:attribute name="entity" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="excelReader">
				<xsd:complexType>
					<xsd:attribute name="sourceParam" />
					<xsd:attribute name="rootPath" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="setContextData" type="d:setContextData_type"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="printContext"/>
		</xsd:choice>
		<xsd:attribute name="cursor" />
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="cursorRootPath" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="executeSql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
		<xsd:attribute name="generatedKeyParam" />
		<xsd:attribute name="affectedCountParam" />
	</xsd:complexType>

	<xsd:complexType name="querySql_type" mixed="true">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlPart" type="d:sqlPart_type" />
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="sqlTrim" type="d:sqlTrim_type" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="setContextData_type">
		<xsd:attribute name="targetPath" />
		<xsd:attribute name="value" />
		<xsd:attribute name="sourcePath" />
	</xsd:complexType>

	<xsd:complexType name="batchExecuteSql_type" mixed="true">
		<xsd:attribute name="sourcePath" />
		<xsd:attribute name="affectedCountParam" />
		<xsd:attribute name="batchSize" />
		<xsd:attribute name="item" />
		<xsd:attribute name="index" />
	</xsd:complexType>

	<xsd:complexType name="java_type">
		<xsd:attribute name="className" />
		<xsd:attribute name="method" />
	</xsd:complexType>

	<xsd:complexType name="collisionSql_type">
		<xsd:attribute name="where" use="required" />
		<xsd:attribute name="message" />
		<xsd:attribute name="code" />
	</xsd:complexType>

</xsd:schema>

=== nfwork/dbfound/src/test/resources/model/test/execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://dbfound.googlecode.com/model https://raw.githubusercontent.com/nfwork/dbfound/master/tags/model.xsd">

    <execute>
        <param name="role_id" dataType="number" ioType="out" />
        <param name="user_id" dataType="varchar" ioType="out" />
        <param name="user_name" dataType="varchar" ioType="out" />
        <param name="fields_size" dataType="number" sourcePath="fields.size" value="0" />
		<sqls>
			<collisionSql where="${@role} is null" message="role不能为空" code="10010" />
            <querySql>
				select ${@role} as role_id
			</querySql>
            <whenSql when="${@fields_size} > 0">
                <querySql>
                    select
                    <sqlPart type="for" sourcePath="fields">
                        ${@value} as #{@code}
                    </sqlPart>
                </querySql>
                <executeSql>
                    select
                    <sqlPart type="for" sourcePath="fields">
                        ${@value} as #{@code}
                    </sqlPart>
                </executeSql>
			</whenSql>
		</sqls>
	</execute>

    <execute name="mt">
        <param name="role_id" dataType="number" ioType="out" />
        <sqls>
            <collisionSql where="${@role} is null" message="role不能为空" code="10010" />
            <querySql>
                select ${@role} as role_id
            </querySql>
        </sqls>
    </execute>

    <execute name="forPart">
        <param name="user_id" dataType="varchar" ioType="out" />
        <param name="user_name" dataType="varchar" ioType="out" />
        <sqls>
            <querySql>
                select
                <sqlPart type="for" sourcePath="fields1">
                    ${@value} as #{@code}
                </sqlPart>
                <sqlPart type="for" sourcePath="fields1" index="index" begin=", ">
                    ${@value} as #{@code}_#{@index}
                </sqlPart>
            </querySql>
            <executeSql>
                select
                <sqlPart type="for" sourcePath="fields2">
                    ${@value} as #{@code}
                </sqlPart>
            </executeSql>
            <querySql>
                select
                <sqlPart type="for" sourcePath="fields1">
                    ${@value} as #{@code}
                </sqlPart>
            </querySql>
        </sqls>
    </execute>

    <execute name="ifPart">
        <param name="user_id" dataType="varchar" ioType="both" />
        <param name="user_name" dataType="varchar" ioType="both" />
		<sqls>
            <querySql>
                select
                <sqlTrim>
                    <sqlPart type="if" sourcePath="user_id">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null">
                        '10010' as user_code,
                    </sqlPart>
                </sqlTrim>
            </querySql>
			<executeSql>
                select
                <sqlTrim>
                    <sqlPart type="if" sourcePath="user_id">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null">
                        '10010' as user_code,
                    </sqlPart>
			    </sqlTrim>
			</executeSql>
            <executeSql>
                select
                    <sqlPart type="if" sourcePath="user_id" autoClearComma="true">
                        1 as user_id,
                    </sqlPart>
                    <sqlPart type="if" sourcePath="user_name" autoClearComma="true">
                        'lily' as user_name,
                    </sqlPart>
                    <sqlPart type="if" condition="${@user_code} is not null" autoClearComma="true">
                        '10010' as user_code,
                    </sqlPart>
            </executeSql>
		</sqls>
	</execute>

    <execute name="batchSql">
        <param name="user_id_0" ioType="out" scope="outParam" />
        <param name="user_id_1" ioType="out" scope="outParam" />
		<sqls>
			<batchSql sourcePath="users" item="user_id" index="index">
                <collisionSql where="${@value} is null" message="user_id不能为空" />
				<querySql>
					select ${@user_id} as user_id_#{@index}
				</querySql>
			</batchSql>
		</sqls>
	</execute>

    <execute name="batchExecuteSql">
        <param name="value" dataType="varchar" value="3" />
        <sqls>
            <batchExecuteSql sourcePath="users" item="user_id" index="index" batchSize="3">
                select
                    #BATCH_TEMPLATE_BEGIN#
                    ${@user_id} as user_id_#{@index},
                    #{@value} as value_#{@index}
                    #BATCH_TEMPLATE_END#
			</batchExecuteSql>
            <executeSql>
                select
                <sqlPart type="for" sourcePath="users_copy" index="index" item="user_id">
                    ${@user_id} as user_#{@index}
                </sqlPart>
            </executeSql>
        </sqls>
    </execute>

    <execute name="batchInsert">
        <param name="num" dataType="number" ioType="out"/>
        <sqls>
            <batchExecuteSql sourcePath="roles" item="role_code" index="index" batchSize="2" affectedCountParam="num">
                INSERT INTO sys_role
                (role_code,
                 role_description,
                 create_by,
                 last_update_by,
                 create_date,
                 last_update_date)
                VALUES
                #BATCH_TEMPLATE_BEGIN#
                    (${@role_code},
                    ${@value},
                    1,
                    1,
                    NOW(),
                    NOW())
                #BATCH_TEMPLATE_END#
            </batchExecuteSql>
        </sqls>
    </execute>

    <query name="getRoles">
        <sql>
            select * from sys_role where role_code like 'batch_role%'
        </sql>
    </query>

    <execute name="deleteRoles">
        <param name="delete_num" dataType="number" ioType="out"/>
		<sqls>
			<executeSql affectedCountParam="delete_num">
				delete from sys_role where role_code in (${@roles})
			</executeSql>
		</sqls>
	</execute>

    <execute name="adapter" adapter="dbfound.test.adapter.ExecuteTestAdapter">
        <sqls>
            <querySql>
				select 1 as user_id
			</querySql>
        </sqls>
    </execute>

    <execute name="generatedKey">
        <param name="role_id" dataType="number" ioType="out" />
        <sqls>
            <collisionSql where="exists (select 1 from sys_role where role_code='unit_test_role')" message="测试角色已经存在" />
            <executeSql generatedKeyParam="role_id">
                INSERT INTO sys_role
                (role_code,
                 role_description,
                 create_by,
                 last_update_by,
                 create_date,
                 last_update_date)
                VALUES ('unit_test_role',
                        'unit_test_role',
                        1,
                        1,
                        NOW(),
                        NOW())
			</executeSql>
        </sqls>
    </execute>

    <execute name="affectedCount">
        <param name="delete_num" dataType="number" ioType="out" />
        <sqls>
            <whenSql when="exists (select 1 from sys_role where role_code='unit_test_role')">
                <executeSql affectedCountParam="delete_num">
                    delete from sys_role where role_id = ${@role_id}
                </executeSql>
			</whenSql>
        </sqls>
    </execute>

    <execute name="empty">
        <param name="user_name" dataType="varchar" emptyAsNull="false" ioType="both" />
		<sqls>
			<collisionSql where="${@user_name} is null" message="不能为null，可以为空字符" />
            <batchSql sourcePath="names" item="user_name">
                <collisionSql where="${@user_name} is null" message="不能为null，可以为空字符" />
			</batchSql>
            <querySql>
                select
                <sqlPart type="for" sourcePath="names" item="user_name" index="index">
                    <sqlPart condition="${@user_name} ='' and ${@index} = 0 ">
                        'lucy' as user_name
                    </sqlPart>
                </sqlPart>
            </querySql>
		</sqls>
	</execute>

    <execute name="defaultValue">
        <param name="user_name" dataType="varchar" value="lily" ioType="both" />
        <sqls>
            <collisionSql where="${@user_name} is null or ${@user_name}=''" message="不能为null" />
            <batchSql sourcePath="names" item="user_name">
                <collisionSql where="${@user_name} is null or ${@user_name}=''" message="不能为null" />
            </batchSql>
            <querySql>
                select
                <sqlPart type="for" sourcePath="names" item="user_name" index="index">
                    <sqlPart condition="${@user_name} ='lily' and ${@index} = 0 ">
                        'lucy' as user_name
                    </sqlPart>
                </sqlPart>
            </querySql>
        </sqls>
    </execute>

    <execute name="handleAdapter" adapter="dbfound.test.adapter.HandleExecuteTestAdapter">
        <param name="skip_execute" dataType="varchar" />
        <sqls>
            <querySql>
                select 1 as user_id
            </querySql>
        </sqls>
    </execute>

</model>

=== nfwork/dbfound/WebRoot/WEB-INF/model/manager/fileManager.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://dbfound.googlecode.com/model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dbfound.googlecode.com/model http://dbfound.googlecode.com/svn/tags/v2/model.xsd">

	<execute name="upload">
		<param name="path" dataType="varchar" />
		<param name="file_name" dataType="varchar" />
		<param name="file" dataType="file" />
		<sqls>
			<java className="com.nfwork.test.FileManager"/>
		</sqls>
	</execute>
	
	<execute name="listFile">
		<param name="path" dataType="varchar" />
		<sqls>
			<java className="com.nfwork.test.FileManager" method="listFile"/>
		</sqls>
	</execute>
	
	<execute name="delete">
		<param name="path" dataType="varchar" scope="param" />
		<param name="file_name" dataType="varchar" />
		<sqls>
			<java className="com.nfwork.test.FileManager" method="delete"/>
		</sqls>
	</execute>
	
	<execute name="down">
		<param name="path" dataType="varchar" sourcePath="param.parameters.path" />
		<param name="file_name" dataType="varchar" scope="param" />
		<param name="file" dataType="file" fileSaveType="disk" ioType="out"/>
		<sqls>
			<java className="com.nfwork.test.FileManager" method="down"/>
		</sqls>
	</execute>

</model>
